# Generated by Django 3.0.6 on 2020-05-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200514_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
