# Generated by Django 3.0.6 on 2020-06-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_mask', models.BooleanField()),
                ('feather', models.PositiveIntegerField(blank=True)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('band', models.PositiveIntegerField(blank=True)),
                ('fill_value', models.IntegerField(blank=True)),
                ('threshold', models.PositiveIntegerField(blank=True)),
                ('hole_size', models.PositiveIntegerField(blank=True)),
                ('white_fill', models.PositiveIntegerField(blank=True)),
                ('no_data', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('version', models.PositiveIntegerField()),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('version', models.PositiveIntegerField()),
                ('path', models.CharField(max_length=300)),
                ('extent', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='static')),
                ('takenAt', models.DateTimeField()),
                ('level', models.PositiveIntegerField()),
                ('resolution', models.CharField(max_length=25)),
                ('mask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imagery.Mask')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProjectResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery.Project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery.Resource')),
            ],
            options={
                'unique_together': {('project', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(through='imagery.ProjectResources', to='imagery.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'version')},
        ),
    ]
