# Generated by Django 3.0.6 on 2020-06-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('path', models.CharField(max_length=300)),
                ('extent', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='static')),
                ('takenAt', models.DateTimeField()),
                ('level', models.PositiveIntegerField()),
                ('resolution', models.CharField(max_length=25)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProjectResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery.Project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery.Resource')),
            ],
            options={
                'unique_together': {('project', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(through='imagery.ProjectResources', to='imagery.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'version')},
        ),
    ]
