# Generated by Django 3.0.6 on 2020-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='no_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
